### ISSUE TITLE
Spinner on Receive Screen

### ISSUE THREAD

**Issue by lindaayangg** [lindaayangg/Wave-Web#19]
- Add Spinner on Receive screen upload clicking the button

**Comment by davidhqr** [comment]
Which spinner do you want to use?

**Comment by lindaayangg** [comment]
I would like to use the one that matches the mobile design.

**Comment by davidhqr** [comment]
The ScaleLoader one from https://www.react-spinners.com/?

**Comment by lindaayangg** [comment]
Added ScaleLoader
